// Homepage
export const HOME_PAGE_PORTOFOLIO = [
  {
    id: 1,
    slug: 'casa-pet',
    tag: 'Prefeitura',
    title: 'Casa Pet',
    year: '2024-2026',
    ferramentas: 'Canva, Photoshop, GPT-5.4',
    description:
      'Criação de peças gráficas para o programa Casa Pet da prefeitura, incluindo materiais de divulgação para adoção responsável e cuidados com animais.',
    style: 'grid-cols-2 max-[450px]:grid-cols-2',
    aspect: 'aspect-video',
    client: 'Prefeitura Municipal',
    mainBanner: '/casa-pet/2.webp',
    homeImages: [
      '/casa-pet/2.webp',
      '/casa-pet/7.webp',
      '/casa-pet/6.webp',
      '/casa-pet/9.webp',
    ],
    projectImages: [
      '/casa-pet/2.webp',
      '/casa-pet/1.webp',
      '/casa-pet/3.webp',
      '/casa-pet/4.webp',
      '/casa-pet/5.webp',
      '/casa-pet/10.webp',
      '/casa-pet/6.webp',
      '/casa-pet/11.webp',
      '/casa-pet/8.webp',
      '/casa-pet/7.webp',
      '/casa-pet/9.webp',
      '/casa-pet/12.webp',
    ],

    publi: {
      icon: '/instagram.svg',
      social: 'Instagram',
      client: '@casapet',
      data: 'setembro de 2025',
      link: 'https://www.instagram.com/p/DO8VhzADT_j/?igsh=NnIwOTRpc3Y5cWt5',
    },
  },
  {
    id: 2,
    slug: 'neps',
    tag: 'Prefeitura',
    title: 'NEPS',
    year: '2024-2026',
    ferramentas: 'Canva, Photoshop, GPT-5.4',
    description:
      'Design de campanhas educativas e material institucional para o Núcleo de Educação e Promoção à Saúde, com foco em comunicação visual acessível e informativa.',
    style: 'grid-cols-2',
    aspect: 'aspect-square',
    client: 'Prefeitura Municipal',
    mainBanner: '/neps/6.webp',
    homeImages: ['/neps/6.webp', '/neps/8.webp'],
    projectImages: [''],
    publi: {
      icon: '/instagram.svg',
      social: 'Instagram',
      data: 'março de 2025',
      link: '',
    },
  },
  {
    id: 3,
    slug: 'semmai',
    tag: 'Prefeitura',
    title: 'SEMMAI',
    year: '2024-2026',
    ferramentas: 'Canva, Photoshop, GPT-5.4',
    description:
      'Desenvolvimento de materiais visuais para a Secretaria Municipal de Meio Ambiente, com sinalização de áreas de preservação, pedais ecológicos e eventos ambientais.',
    style: 'grid-cols-2',
    aspect: 'aspect-video',
    client: 'Prefeitura Municipal',
    mainBanner: '/casa-pet/7.webp',
    homeImages: [
      '/semmai/1.webp',
      '/semmai/2.webp',
      '/semmai/5.webp',
      '/semmai/6.webp',
    ],
    projectImages: [''],
    publi: {
      icon: '/instagram.svg',
      social: 'Instagram',
      data: 'setembro de 2025',
      link: 'https://www.instagram.com/p/DOv1bg2jRGR/?igsh=MWxkNGZwczlpdTMwMQ==',
    },
  },
  {
    id: 4,
    slug: 'sms',
    tag: 'Prefeitura',
    title: 'SMS',
    year: '2024-2026',
    ferramentas: 'Canva, Photoshop, GPT-5.4',
    description:
      'Peças visuais para a Secretaria Municipal de Saúde, incluindo campanhas de vacinação, eventos sazonais e comunicados oficiais com identidade visual consistente.',
    style: 'grid-cols-2',
    aspect: 'aspect-square',
    client: 'Prefeitura Municipal',
    mainBanner: '/sms/11.webp',
    homeImages: ['/sms/1.webp', '/sms/10.webp'],
    projectImages: [''],
    publi: {
      icon: '/instagram.svg',
      social: 'Instagram',
      data: 'julho de 2025',
      link: 'https://www.instagram.com/p/DMgV7KBRtak/?igsh=NDhnNzQ1Y3ZtcHFi',
    },
  },
  {
    id: 5,
    slug: 'una-volume-1',
    tag: 'Faculdade',
    title: 'UNA — Volume I',
    year: '2023-2026',
    ferramentas: 'Canva, Photoshop, GPT-5.4',
    description:
      'Projetos acadêmicos e criativos desenvolvidos para o Centro Universitário UNA, incluindo ilustrações, artes para eventos e materiais promocionais.',
    style: 'grid-cols-2',
    aspect: 'aspect-video',
    client: 'Faculdade Una',
    mainBanner: '/una/18.webp',
    homeImages: ['/una/9.webp', '/una/18.webp', '/una/23.webp', '/una/12.webp'],
    projectImages: [''],
    publi: {
      icon: '/instagram.svg',
      social: 'Instagram',
      data: 'abril de 2025',
      link: 'https://www.instagram.com/p/DIMdmLNOEiw/?igsh=OGIxa3drd2Z4Y2lv',
    },
  },
  {
    id: 6,
    slug: 'una-volume-2',
    tag: 'Faculdade',
    title: 'UNA — Volume II',
    year: '2023-2026',
    ferramentas: 'Canva, Photoshop, GPT-5.4',
    description:
      'Criação de logotipos e identidade visual para grupos de estudo e projetos acadêmicos, como o GEACEMIV, com guias de cores e aplicações da marca.',
    style: 'grid-cols-2',
    aspect: 'aspect-square',
    client: 'Faculdade Una',
    mainBanner: '/una/23.webp',
    homeImages: ['/una/26.webp', '/una/24.webp'],
    projectImages: [''],
    publi: {
      icon: '/instagram.svg',
      social: 'Instagram',
      data: 'abril de 2025',
      link: '',
    },
  },
  {
    id: 7,
    slug: 'outros-trabalhos',
    tag: 'Freelance',
    title: 'Outros Trabalhos',
    year: '2022-2026',
    ferramentas: 'Canva, Photoshop, GPT-5.4',
    description:
      'Projetos diversos realizados para clientes e causas pessoais, incluindo artes religiosas, ilustrações temáticas e trabalhos de design independentes.',
    style: 'grid-cols-2',
    aspect: 'aspect-video',
    client: 'Clientes Diversos',
    mainBanner: '/others/13.webp',
    homeImages: [
      '/others/7.webp',
      '/others/8.webp',
      '/others/10.webp',
      '/others/13.webp',
    ],
    projectImages: [''],
    publi: {
      icon: '/instagram.svg',
      social: 'Instagram',
      data: 'novembro de 2025',
      link: '',
    },
  },
]

// Especific Page
export type Album = {
  id: string
  title: string
  cover: string
  photos: Array<string>
}

export const albums: Array<Album> = [
  {
    id: '1',
    title: 'PREFEITURA - CASA PET',
    cover: '/casa-pet/1.webp',
    photos: [
      '/casa-pet/2.webp',
      '/casa-pet/1.webp',
      '/casa-pet/3.webp',
      '/casa-pet/4.webp',
      '/casa-pet/5.webp',
      '/casa-pet/10.webp',
      '/casa-pet/6.webp',
      '/casa-pet/11.webp',
      '/casa-pet/8.webp',
      '/casa-pet/7.webp',
      '/casa-pet/9.webp',
      '/casa-pet/12.webp',
    ],
  },
  {
    id: '2',
    title: 'PREFEITURA - NEPS',
    cover: '/neps/6.webp',
    photos: [
      '/neps/8.webp',
      '/neps/2.webp',
      '/neps/3.webp',
      '/neps/4.webp',
      '/neps/1.webp',
      '/neps/6.webp',
      '/neps/7.webp',
    ],
  },
  {
    id: '3',
    title: 'PREFEITURA - SMS ',
    cover: '/sms/11.webp',
    photos: [
      '/sms/1.webp',
      '/sms/2.webp',
      '/sms/3.webp',
      '/sms/4.webp',
      '/sms/5.webp',
      '/sms/6.webp',
      '/sms/7.webp',
      '/sms/8.webp',
      '/sms/9.webp',
      '/sms/10.webp',
      '/sms/11.webp',
    ],
  },
  {
    id: '4',
    title: 'PREFEITURA - SEMMAI',
    cover: '/semmai/2.webp',
    photos: [
      '/semmai/1.webp',
      '/semmai/2.webp',
      '/semmai/3.webp',
      '/semmai/4.webp',
      '/semmai/5.webp',
      '/semmai/6.webp',
    ],
  },
  {
    id: '5',
    title: 'FACULDADE - (UNA) I',
    cover: '/una/6.webp',
    photos: [
      '/una/14.webp',

      '/una/2.webp',
      '/una/3.webp',
      '/una/1.webp',
      '/una/5.webp',
      '/una/4.webp',
      '/una/7.webp',
      '/una/8.webp',
      '/una/9.webp',
      '/una/10.webp',
      '/una/11.webp',
      '/una/12.webp',
      '/una/13.webp',
      '/una/6.webp',
    ],
  },
  {
    id: '6',
    title: 'FACULDADE -(UNA) II',
    cover: '/una/23.webp',
    photos: [
      '/una/18.webp',
      '/una/24.webp',
      '/una/16.webp',
      '/una/17.webp',
      '/una/18.webp',
      '/una/19.webp',
      '/una/20.webp',
      '/una/21.webp',
      '/una/22.webp',
      '/una/23.webp',
      '/una/26.webp',
      '/una/27.webp',
      '/una/15.webp',
    ],
  },
  {
    id: '7',
    title: 'OUTROS TRABALHOS',
    cover: '/others/13.webp',
    photos: [
      '/others/8.webp',
      '/others/2.webp',
      '/others/1.webp',
      '/others/5.webp',
      '/others/6.webp',
      '/others/7.webp',
      '/others/8.webp',
      '/others/9.webp',
      '/others/10.webp',
      '/others/11.webp',
      '/others/12.webp',
      '/others/13.webp',
      '/others/14.webp',
      '/others/15.webp',
    ],
  },
]
