export type Album = {
  id: string
  title: string
  cover: string
  photos: Array<string>
}

export const albums: Array<Album> = [
  {
    id: '1',
    title: 'PREFEITURA - CASA PET',
    cover: '/casa-pet/1.png',
    photos: [
      '/casa-pet/2.png',
      '/casa-pet/1.png',
      '/casa-pet/3.png',
      '/casa-pet/4.png',
      '/casa-pet/5.png',
      '/casa-pet/10.png',
      '/casa-pet/6.png',
      '/casa-pet/11.png',
      '/casa-pet/8.png',
      '/casa-pet/7.png',
      '/casa-pet/9.png',
    ],
  },
  {
    id: '2',
    title: 'PREFEITURA - NEPS',
    cover: '/neps/4.png',
    photos: [
      '/neps/5.png',
      '/neps/2.png',
      '/neps/3.png',
      '/neps/4.png',
      '/neps/1.png',
      '/neps/6.png',
      '/neps/7.png',
      '/neps/8.png',
    ],
  },
  {
    id: '3',
    title: 'PREFEITURA - SMS ',
    cover: '/sms/8_.png',
    photos: [
      '/sms/7_.png',
      '/sms/1_.png',
      '/sms/2_.png',
      '/sms/3_.png',
      '/sms/4_.png',
      '/sms/5_.png',
      '/sms/6_.png',
      '/sms/8_.png',
      '/sms/9_.png',
      '/sms/10_.png',
      '/sms/11_.png',
    ],
  },
  {
    id: '4',
    title: 'PREFEITURA - SEMMAI',
    cover: '/semmai/1_.png',
    photos: [
      '/semmai/5_.png',
      '/semmai/1_.png',
      '/semmai/3_.png',
      '/semmai/4_.png',
      '/semmai/2_.png',
      '/semmai/6_.png',
    ],
  },
  {
    id: '5',
    title: 'FACULDADE - (UNA) I',
    cover: '/una/22.png',
    photos: [
      '/una/4_.png',
      '/una/2_.png',
      '/una/3_.png',
      '/una/1_.png',
      '/una/5_.png',
      '/una/6_.png',
      '/una/7_.png',
      '/una/8_.png',
      '/una/9_.png',
      '/una/10_.png',
      '/una/11_.png',
      '/una/12_.png',
      '/una/13_.png',
      '/una/14_.png',
    ],
  },
  {
    id: '6',
    title: 'FACULDADE -(UNA) II',
    cover: '/una/24.png',
    photos: [
      '/una/25.png',
      '/una/24.png',
      '/una/16_.png',
      '/una/17_.png',
      '/una/18_.png',
      '/una/19_.png',
      '/una/20.png',
      '/una/21.png',
      '/una/22.png',
      '/una/23.png',
      '/una/26.png',
      '/una/27.png',
      '/una/15_.png',
    ],
  },
  {
    id: '7',
    title: 'OUTROS TRABALHOS',
    cover: '/others/1.png',
    photos: [
      '/others/4.png',
      '/others/1.png',
      '/others/3.png',
      '/others/5.png',
      '/others/6.png',
      '/others/7.png',
      '/others/9.png',
      '/others/10.png',
      '/others/11.png',
      '/others/12.png',
      '/others/13.png',
      '/others/14.png',
      '/others/15.png',
      '/others/16.png',
      '/others/17.png',
    ],
  },
]
